feat: pr

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -113,6 +113,29 @@ jobs:
             -Dsonar.organization=${{ secrets.SONAR_ORG }} \
             -Dsonar.token=${{ secrets.SONAR_TOKEN }}
 
+  check_coverage:
+    runs-on: ubuntu-latest
+    needs: sonar
+    if: github.event_name == 'pull_request'
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+
+      - name: SonarQube Quality Gate Check
+        run: |
+          # Consultando o status do Quality Gate
+          sonar_status=$(curl -s -u ${{ secrets.SONAR_TOKEN }} "https://sonarcloud.io/api/qualitygates/project_status?projectKey=kaiquemotta_production")
+          
+          # Verificando o status do Quality Gate (pode ser 'OK' ou 'ERROR')
+          quality_gate_status=$(echo $sonar_status | jq -r '.projectStatus.status')
+          
+          if [ "$quality_gate_status" != "OK" ]; then
+            echo "SonarQube Quality Gate failed: Coverage is below 70%" && exit 1
+          else
+            echo "SonarQube Quality Gate passed!"
+          fi
+
   deploy_pre:
     runs-on: ubuntu-22.04
     needs: sonar
@@ -152,26 +175,3 @@ jobs:
           heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
           heroku_app_name: "production-orders"
           heroku_email: "kaique.motta@hotmail.com"
-
-check_coverage:
-  runs-on: ubuntu-latest
-  needs: test
-  if: github.event_name == 'pull_request'
-  steps:
-    - uses: actions/checkout@v4
-      with:
-        fetch-depth: 0
-
-    - name: SonarQube Quality Gate Check
-      run: |
-        # Consultando o status do Quality Gate
-        sonar_status=$(curl -s -u ${{ secrets.SONAR_TOKEN }} "https://sonarcloud.io/api/qualitygates/project_status?projectKey=kaiquemotta_production")
-        
-        # Verificando o status do Quality Gate (pode ser 'OK' ou 'ERROR')
-        quality_gate_status=$(echo $sonar_status | jq -r '.projectStatus.status')
-        
-        if [ "$quality_gate_status" != "OK" ]; then
-          echo "SonarQube Quality Gate failed: Coverage is below 70%" && exit 1
-        else
-          echo "SonarQube Quality Gate passed!"
-        fi
